apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mykPhilips/argo-cd.git
    targetRevision: main
    path: dev
    repoAuthSecret:
      name: argocd-github-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
