apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: default
spec:
  project: default
  source:
    repoURL: https://github.com/mykPhilips/argo-cd.git
    targetRevision: HEAD
    path: kafka
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
